/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/idevz/crd-start/pkg/apis/crdstart/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDcreaters implements DcreaterInterface
type FakeDcreaters struct {
	Fake *FakeCrdstartV1alpha1
	ns   string
}

var dcreatersResource = schema.GroupVersionResource{Group: "crdstart.idevz.org", Version: "v1alpha1", Resource: "dcreaters"}

var dcreatersKind = schema.GroupVersionKind{Group: "crdstart.idevz.org", Version: "v1alpha1", Kind: "Dcreater"}

// Get takes name of the dcreater, and returns the corresponding dcreater object, and an error if there is any.
func (c *FakeDcreaters) Get(name string, options v1.GetOptions) (result *v1alpha1.Dcreater, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dcreatersResource, c.ns, name), &v1alpha1.Dcreater{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dcreater), err
}

// List takes label and field selectors, and returns the list of Dcreaters that match those selectors.
func (c *FakeDcreaters) List(opts v1.ListOptions) (result *v1alpha1.DcreaterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dcreatersResource, dcreatersKind, c.ns, opts), &v1alpha1.DcreaterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DcreaterList{ListMeta: obj.(*v1alpha1.DcreaterList).ListMeta}
	for _, item := range obj.(*v1alpha1.DcreaterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dcreaters.
func (c *FakeDcreaters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dcreatersResource, c.ns, opts))

}

// Create takes the representation of a dcreater and creates it.  Returns the server's representation of the dcreater, and an error, if there is any.
func (c *FakeDcreaters) Create(dcreater *v1alpha1.Dcreater) (result *v1alpha1.Dcreater, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dcreatersResource, c.ns, dcreater), &v1alpha1.Dcreater{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dcreater), err
}

// Update takes the representation of a dcreater and updates it. Returns the server's representation of the dcreater, and an error, if there is any.
func (c *FakeDcreaters) Update(dcreater *v1alpha1.Dcreater) (result *v1alpha1.Dcreater, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dcreatersResource, c.ns, dcreater), &v1alpha1.Dcreater{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dcreater), err
}

// Delete takes name of the dcreater and deletes it. Returns an error if one occurs.
func (c *FakeDcreaters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dcreatersResource, c.ns, name), &v1alpha1.Dcreater{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDcreaters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dcreatersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DcreaterList{})
	return err
}

// Patch applies the patch and returns the patched dcreater.
func (c *FakeDcreaters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Dcreater, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dcreatersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Dcreater{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Dcreater), err
}
