/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/idevz/crd-start/pkg/apis/crdstart/v1alpha1"
	scheme "github.com/idevz/crd-start/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DcreatersGetter has a method to return a DcreaterInterface.
// A group's client should implement this interface.
type DcreatersGetter interface {
	Dcreaters(namespace string) DcreaterInterface
}

// DcreaterInterface has methods to work with Dcreater resources.
type DcreaterInterface interface {
	Create(*v1alpha1.Dcreater) (*v1alpha1.Dcreater, error)
	Update(*v1alpha1.Dcreater) (*v1alpha1.Dcreater, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Dcreater, error)
	List(opts v1.ListOptions) (*v1alpha1.DcreaterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Dcreater, err error)
	DcreaterExpansion
}

// dcreaters implements DcreaterInterface
type dcreaters struct {
	client rest.Interface
	ns     string
}

// newDcreaters returns a Dcreaters
func newDcreaters(c *CrdstartV1alpha1Client, namespace string) *dcreaters {
	return &dcreaters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dcreater, and returns the corresponding dcreater object, and an error if there is any.
func (c *dcreaters) Get(name string, options v1.GetOptions) (result *v1alpha1.Dcreater, err error) {
	result = &v1alpha1.Dcreater{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dcreaters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Dcreaters that match those selectors.
func (c *dcreaters) List(opts v1.ListOptions) (result *v1alpha1.DcreaterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DcreaterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dcreaters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dcreaters.
func (c *dcreaters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dcreaters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dcreater and creates it.  Returns the server's representation of the dcreater, and an error, if there is any.
func (c *dcreaters) Create(dcreater *v1alpha1.Dcreater) (result *v1alpha1.Dcreater, err error) {
	result = &v1alpha1.Dcreater{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dcreaters").
		Body(dcreater).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dcreater and updates it. Returns the server's representation of the dcreater, and an error, if there is any.
func (c *dcreaters) Update(dcreater *v1alpha1.Dcreater) (result *v1alpha1.Dcreater, err error) {
	result = &v1alpha1.Dcreater{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dcreaters").
		Name(dcreater.Name).
		Body(dcreater).
		Do().
		Into(result)
	return
}

// Delete takes name of the dcreater and deletes it. Returns an error if one occurs.
func (c *dcreaters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dcreaters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dcreaters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dcreaters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dcreater.
func (c *dcreaters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Dcreater, err error) {
	result = &v1alpha1.Dcreater{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dcreaters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
